words = [
    "돼",
    "안 돼.",
    "포기해.",
    "다시 한 번 물어봐.",
    "허락할게.",
    "당장 시작해.",
    "나중에 해.",
    "안. 돼.",
    "하지마.",
    "그래.",
    "가만히 있어.",
    "그것도 안 돼.",
    "응.",
    "아니.",
    "하고 싶은 대로 해.",
    "그것도 하지마.",
    "왜?",
    "마음대로 해.",
    "꿈도 꾸지 마.",
    "기다려."
]